services:
  jupyterlab:
    build:
      context: .
      dockerfile: docker/Dockerfile.jupyter
    image: gcp_jupyter_pyspark:latest
    container_name: gcp_jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jupyteruser/notebooks
    env_file:
      - .env.dev
    user: "${LOCAL_UID}:${LOCAL_GID}"
    command: ["sh", "-c", "jupyter lab --ip=0.0.0.0 --no-browser --NotebookApp.token='${JUPYTER_TOKEN}'"]

  etl_runner:
    # Remove build context, since the image will be pre-built via Ansible
    image: gcp_etl_runner:latest  # Make sure to use the pre-built image from Ansible
    container_name: gcp_etl_runner
    volumes:
      - gcp_datamigration:/home/etl_user/jobs-output
    env_file:
      - .env.prod
    tty: true
    stdin_open: true
    user: "${LOCAL_UID}:${LOCAL_GID}"  # Make sure your local UID:GID match your host user
    working_dir: /app

  etl_test:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev-ubuntu
    image: gcp_etl_test:latest
    container_name: gcp_etl_test_runner
    volumes:
      - ./:/app
    working_dir: /app
    command: ["pytest", "tests/", "--maxfail=3", "--disable-warnings", "-q"]
    env_file:
      - .env.test
    user: "${LOCAL_UID}:${LOCAL_GID}"

volumes:
  gcp_datamigration:
