services:
  jupyterlab:
    build:
      context: .
      dockerfile: docker/Dockerfile.jupyter
    image: gcp_jupyter_pyspark:latest
    container_name: gcp_jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jupyteruser/notebooks
    env_file:
      - .env.dev
    user: "${UID}:${GID}"

  etl_runner:
    build:
      context: .
      dockerfile: Dockerfile.jenkins  # Adjust if you named it differently
    image: gcp_etl_runner:latest
    container_name: gcp_etl_runner
    volumes:
      - gcp_datamigration:/home/etl_user/jobs-output
    env_file:
      - .env.prod
    tty: true
    stdin_open: true
    user: "${UID}:${GID}"

  etl_test:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev-ubuntu  # Adjust if needed
    image: gcp_etl_runner:latest
    container_name: gcp_etl_test_runner
    volumes:
      - ./:/app
    working_dir: /app
    command: ["pytest", "tests/", "--maxfail=3", "--disable-warnings", "-q"]
    env_file:
      - .env.test

volumes:
  gcp_datamigration:
