services:
  etl_test:
    build:
      context: .
      dockerfile: docker/Dockerfile.ubuntu
    image: gcp_etl_test:latest
    container_name: gcp_etl_test_runner
    volumes:
      - ./:/app
      - test_data:/app/data   # persistent volume for test outputs
    working_dir: /app
    command: ["pytest", "tests/", "--maxfail=3", "--disable-warnings", "-q", "--junitxml=/app/data/test-results.xml"]
    env_file:
      - env/.env.test
    user: "${LOCAL_UID}:${LOCAL_GID}"

volumes:
  test_data:
