- name: Build Docker image
  community.general.docker_image:
    name: "{{ image_name }}"
    tag: "{{ env }}"
    build:
      path: "{{ playbook_dir }}/../../"
      dockerfile: >-
        {{
          'docker/Dockerfile.dev-ubuntu'
          if env == 'dev' else
          'Dockerfile.jenkins'
        }}
      pull: yes
      nocache: yes
