---
- name: Setup GCP resources
  hosts: localhost
  gather_facts: no
  vars:
    gcp_project_id: "your-gcp-project-id"
    artifact_registry_name: "my-etl-repo"
    artifact_registry_location: "us-central1"
    service_account_name: "etl-service-account"
    gcs_bucket_name: "my-etl-bucket"
    service_account_file: "/path/to/your/service/account/key.json"
    env_file_template: ".env.j2"

  tasks:
    - name: Create Artifact Registry repository
      gcp_artifact_registry:
        name: "{{ artifact_registry_name }}"
        location: "{{ artifact_registry_location }}"
        project: "{{ gcp_project_id }}"
        service_account_file: "{{ service_account_file }}"
        state: present

    - name: Create Service Account
      gcp_iam_service_account:
        name: "{{ service_account_name }}"
        project: "{{ gcp_project_id }}"
        service_account_file: "{{ service_account_file }}"
        state: present

    - name: Assign IAM role to the service account
      gcp_iam_service_account_role:
        service_account_email: "{{ service_account_email }}"
        role: "roles/artifactregistry.writer"
        project: "{{ gcp_project_id }}"
        service_account_file: "{{ service_account_file }}"
        state: present

    - name: Create GCS bucket
      gcp_storage_bucket:
        name: "{{ gcs_bucket_name }}"
        project: "{{ gcp_project_id }}"
        location: "US"
        service_account_file: "{{ service_account_file }}"
        state: present

    - name: Template .env file
      template:
        src: "{{ env_file_template }}"
        dest: "/home/etl_user/.env"
